# Site settings
title: Angular Google Chart
email: your-email@domain.com
description: Wrapper directive for Google Charts API in AngularJS.
baseurl: "/angular-google-chart" # the subpath of your site, e.g. /blog/
url: "https://angular-google-chart.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  angular-google-chart

# Build settings
markdown: kramdown

latest_version: 1.0.0-beta.1
available_versions:
    - 1.0.0-beta.1
    - 0.1.0
    - 0.1.0-beta.2
    - 0.1.0-beta.1
    - 0.0.11

collections:
    docs:
        output: true
        permalink: "docs/:path/"
